site_name: Parallel Agents
site_description: A server-client architecture for parallel AI agents with Block Goose and Claude Code support
site_url: https://shouhanzen.github.io/parallel_agents/
repo_url: https://github.com/shouhanzen/parallel_agents
repo_name: shouhanzen/parallel_agents

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
    - Overview: README.md
    - Installation: development.md
    - Quick Start: user-guide.md
  - Architecture:
    - System Design: architecture.md
    - API Reference: api-reference.md
  - Development:
    - Contributing: development.md
    - Code Review: code-review.md
  - Review:
    - Architecture Review: review/architecture.md
    - Testing Review: review/testing.md
    - Documentation Review: review/documentation.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shouhanzen/parallel_agents
  version:
    provider: mike 